# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "MMR Lab"
title_separator: "-"
name: "MMR Lab"

description: "Microbiology and Molecular Research"

url: "https://mmr-lab.github.io"
baseurl: ""
repository: "mmr-lab/mmrlab.github.io"

author:
  avatar: "profile.png"
  name: "Dr. Md Masuder Rahman, PhD"
  bio: "Principal Investigator & Professor in the Department of Biotechnology and Genetic Engineering at Mawlana Bhashani Science and Technology University."
  location: "MBSTU, Tangail, Bangladesh"
  employer: "Mawlana Bhashani Science and Technology University"
  email: "your-email@example.com"

  googlescholar: "https://scholar.google.com/citations?user=scWR7ywAAAAJ&hl=en"
  orcid: "https://orcid.org/yourorcidurl"

  github: "mmr-lab"
  linkedin: ""
  twitter: ""
  instagram: ""

publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - node_modules
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"

markdown: kramdown
highlighter: rouge

collections:
  publications:
    output: true
  projects:
    output: true
  team:
    output: true
  alumni:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: team
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: alumni
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

timezone: Etc/UTC
